<?php

namespace AppBundle\Repository;

/**
 * ItemOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemOrderRepository extends \Doctrine\ORM\EntityRepository
{
}
